spring:
    datasource:
        url: jdbc:h2:mem:ch4njun
        driver-class-name: org.h2.Driver
        username: sa
        password:
        platform: org.hibernate.dialect.H2Dialect

    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    profiles:
        active: local-dev